applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="departamento_app"

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
    'departamento-lista/',
    views.DepartamentoListView.as_view(),
    name='departamento_list' ),
    path('new-departamento/', 
    views.NewDepartamentoView.as_view(), 
    name='nuevo_departamento/'
    ),
]

applications/personas/urls.py
from django.urls import path
from .views import ( lisAllEmpleados,
ListByAreaEmpleado,
ListEmpleadoByKword,
ListHabilidadesEmpleados,
EmpleadoDetailView,                    
EmpleadoCreateView,
SuccessView, EmpleadoUpdateView,EmpleadoDeleteView,InicioView, ListaEmpleadosAdmin,

)

app_name='persona_app'

urlpatterns = [
    path('', InicioView.as_view()),
    path('listar-todos-empleados/', lisAllEmpleados.as_view()),
    path('buscar-empleado/', ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', ListHabilidadesEmpleados.as_view()),
    path(
    'ver-empleado/<pk>/',
    EmpleadoDetailView.as_view(),
    name='empleado_detail'
),

    path('add-empleado/', 
        EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path(
        'success/',
        SuccessView.as_view(),
        name='correcto'),
    path(
        'update-empleado/<pk>/',
        EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path(
        'delate-empleado/<pk>/',
        EmpleadoDeleteView.as_view(),
        name='Eliminar_empleado'),
    path(
        'ver-empleado/<pk>/',
        EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),

    path(
        'list-by-area/<subnombre>/',
        ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),

    path(
        'lista-empleados-admin/',
        ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from applications.departamento import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path('', include('applications.home.urls')),  # ahora la raíz '' apunta a home
    re_path('', include('applications.personas.urls')),
    re_path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li>
        <a href="/listar-todos-empleados/">Listar</a> 
        </li>
          <li><a href="{% url 'departamento_app:departamento_list' %}">Departamento</a></li>
          <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
          <li><a href="/new-departamento/">Nuevo Departamento</a></li>
        </ul>
     
  
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar Empleado"></li>
      <a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar nuevo</a>
    </ul>
  </div>
</div>