applications/personas/urls.py
from django.urls import path
from .views import ( lisAllEmpleados,
ListByAreaEmpleado,
ListEmpleadoByKword,
ListHabilidadesEmpleados,
EmpleadoDetailView,                    
EmpleadoCreateView,
SuccessView, EmpleadoUpdateView,EmpleadoDeleteView,InicioView, ListaEmpleadosAdmin,

)

app_name='persona_app'

urlpatterns = [
    path('', InicioView.as_view()),
    path('listar-todos-empleados/', lisAllEmpleados.as_view()),
    path('buscar-empleado/', ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', ListHabilidadesEmpleados.as_view()),
    path(
    'ver-empleado/<pk>/',
    EmpleadoDetailView.as_view(),
    name='empleado_detail'
),

    path('add-empleado/', 
        EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path(
        'success/',
        SuccessView.as_view(),
        name='correcto'),
    path(
        'update-empleado/<pk>/',
        EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path(
        'delate-empleado/<pk>/',
        EmpleadoDeleteView.as_view(),
        name='Eliminar_empleado'),
    path(
        'ver-empleado/<pk>/',
        EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),

    path(
        'list-by-area/<subnombre>/',
        ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),

    path(
        'lista-empleados-admin/',
        ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from applications.departamento import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path('', include('applications.home.urls')),  # ahora la raíz '' apunta a home
    re_path('', include('applications.personas.urls')),
    re_path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/personas/models.py
from django.db import models
from ckeditor.fields import RichTextField
from applications.departamento.models import Departamento

# Create your models here.

class Habilidad(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades de empleados'

    def __str__(self):
        return f"{self.id} - {self.habilidad}"


class Empleado(models.Model):

    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
    )

    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombres completos', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidad)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name', 'last_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return f"{self.id} - {self.first_name} {self.last_name}"

applications/personas/forms.py
from django import forms
from .models import Empleado


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model= Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/personas/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import (ListView,
DetailView,
CreateView,
TemplateView,
UpdateView,
DeleteView)
from .models import Empleado
from .forms import EmpleadoForm 

class InicioView(TemplateView):
    template_name='persona/inicio.html'


class ListaEmpleadosAdmin(ListView):
    template_name='persona/lista_empleados.html'
    paginate_by= 10
    ordering='first_name'
    context_object_name='empleados'
    model=Empleado

class lisAllEmpleados(ListView):
    paginate_by=4
    ordering='last_name'
    template_name = "persona/list.all.html" 

    def get_queryset(self):
        #print('**********************')
        palabra_clave = self.request.GET.get('kword', '') 
        #print('**********************', palabra)
        lista=Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista
    


class ListByAreaEmpleado(ListView):
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['subnombre']
        lista=Empleado.objects.filter(
            departamento__subnombre__iexact=area
        )
        return lista


class ListEmpleadoByKword(ListView):
    model = Empleado                    
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'  

    def get_queryset(self):
        #print('**********************')
        palabra_clave = self.request.GET.get('kword', '') 
        #print('**********************', palabra)
        lista=Empleado.objects.filter(first_name=palabra_clave)
        return lista
    
class ListHabilidadesEmpleados(ListView):
    template_name='persona/habilidades.html'
    context_object_name='habilidades'

    def get_queryset(self):
        empleado=Empleado.objects.get(id=5)
        return empleado.habilidades.all()
    
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detail_empleado.html'
    context_object_name = 'empleado'


    def get_context_data(self, **kwargs):
        context=super(EmpleadoDetailView,self).get_context_data(**kwargs )
        context['titulo'] = 'Empleado del mes'
        return context
    
class SuccessView(TemplateView):
    template_name='persona/success.html'


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = 'persona/add.html'
    success_url = reverse_lazy('persona_app:correcto')

    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar',
    ]

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super().form_valid(form)

    

class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = 'persona/update.html'
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades'
    ]
    success_url = reverse_lazy('persona_app:correcto')   

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('**********************METHODO POST*************************')
        print(request.POST)
        print(request.POST['last_name'])

        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        print('*******METODO FORM VALID*******')
        self.object = form.save()
        return super().form_valid(form) 
    
class EmpleadoDeleteView(DeleteView):
    model=Empleado
    template_name='persona/delate.html'
    success_url = reverse_lazy('persona_app:empleados_admin')   

templates/persona/add.html
{% extends 'base.html' %}

{% block blockname %}
    Registrar empleado
{% endblock blockname %}

{% block content %}
    {% include "include/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Registrar empleado
        </h1>
        <div class="cell">
            <form class="cell grid-x grid-margin-x" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo:
                        {{ form.job }} 
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Habilidades:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>foto:
                        {{ form.avatar }}
                    </label>
                </div>
                
                 <button type="submit" class="button success" >Agregar</button>
                 </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar Empleados por palabra clave</h1>

<form method="GET">{%  csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>

    <h3>Lista de resultados</h3>
    <ul>
       {% for e in empleados %}
    <li>{{ e }}</li>
    {% endfor %}

    </ul>
        
</form>

templates/persona/delate.html
{% extends 'base.html' %}


{% block title %}
    Eliminar empleado
{% endblock title %}


{% block content %}


{% include "include/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{object.first_name}} {{object.last_name}}</h1>

        <form class="grid-x" method="post">{% csrf_token %}
        
        
        
            <div class="callout secondary">
  <h5>¿Confirme que deceas eliminar al empleado?</h5>
<button type="submit" class="alert button">Confirmar</button>
</div>
        
        
            
        </form>
    </div>
</div>
{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include "include/header.html" %}

<div class="grid-container">
    <div class="grid-x align-center">
        <div class="cell large-4 card">

            <div class="card-divider">
                {{ empleado.get_job_display }}
            </div>

            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}
                <img src="{% static 'img/img4.jpg' %}">
            {% endif %}

            <div class="card-section">
                <h4>{{ empleado.full_name }}</h4>
                <p>{{ empleado.departamento }}</p>

                <p><strong>Habilidades:</strong></p>
                <ul>
                    {% for h in empleado.habilidades.all %}
                        <li>{{ h }}</li>
                    {% empty %}
                        <li>Sin habilidades</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/persona/habilidades.html
<h1>Habilidades del empleado</h1>

<ul>
    {% for h in habilidades %}
        <li>{{ habilidades }}</li>
    {% endfor %}
</ul>

templates/persona/inicio.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
Página de inicio del sistema empleados
{% endblock title %}

{% block content %}

{% include 'include/header.html' %}


<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
  <div class="orbit-wrapper">
    <div class="orbit-controls">
      <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
      <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
    </div>
    <ul class="orbit-container">
      <li class="is-active orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/img4.jpg' %}" width="100px">
          <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
        </figure>
      </li>
      <li class="orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/img5.jpg' %}" width="100px" >
          <figcaption class="orbit-caption">Lets Rocket!</figcaption>
        </figure>
      </li>
    </ul>
  </div>
</div>




<div class="grid-container">
    <div class="grid-x grid-padding-x align-center">
    <div class="cell small-12 medium-10 larger-8">
  <h1 class="text-center" style="font-size: 2rem; margin-bottom: 2rem;">
    Bienvenido al sistema de Registro  de Empleados
 </h1>
    </div>


<div class="cell small-12 medium-8 larger-6">
    <div class="callout success">

        <h5>Registrar y control de empleados</h5>
        <p>It has an easy to override visual style, and is appropriately subdued</p>
        <a href="#" class="button">Ver empleados</a>
      </div>
    </div>
</div>
</div>


{% endblock content %}

templates/persona/list.all.html
{% extends 'base.html' %}

{% block content %}

{% include 'include/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de empleados</h1>
        <form class=" cell grid-x grid-margin-x" method="get">{% csrf_token %}
            <div class="cell-large-7">
                <input type="text" id="kword" name="kword" placeholder=" buscar empleado">
            </div>
            <div class="cell-large-2">
                <button type="button" class="success button">Buscar</button>
            </div>
          </form>
        <div class="cell">
            <table>
  <thead>
    <tr>
      <th width="200">ID</th>
      <th>NOMBRES</th>
      <th width="150">APELLIDOS</th>
      <th width="150">DEPARTAMENTO</th>
      <th width="150">ACCION</th>

    </tr>
  </thead>
  <tbody>
        {% for empleado in object_list %}
    <tr>
      <td>{{ empleado.id }}</td>
      <td>{{ empleado.first_name }}</td>
      <td>{{ empleado.last_name }}</td>
      <td>{{ empleado.departamento }}</td>
      <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.id %}">Ver</a>
</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<div class="cell">
  {% if is_paginated %}
  <nav aria-label="Pagination">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="pagination-previous">
      <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
    </li>
    {% endif %}

    {% for pagina in paginator.page_range %}
      {% if pagina == page_obj.number %}
          <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
        {% else %}
          <li><a href="?page={{pagina}}">{{ pagina }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="pagination-next">
          <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
        </li>
    {% endif %}


   
  </ul>
</nav>
{% endif %}
 </div>
    </div>
</div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block blockname %}
    lista empleados por departamento
{% endblock blockname %}

{% block content %}
    {% include "include/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area:</div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="150">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empleado in empleados %}
                        <tr>
                            <td>{{ empleado.id }}</td>
                            <td>{{ empleado.first_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento }}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.id %}">ver</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}


<h1>Lista de todos los empleados</h1>

<ul>
    {% for empleado in object_list %}
        <li>
            {{ empleado.first_name }} {{ empleado.last_name }}
            — Área: {{ empleado.departamento.subnombre }}
        </li>
    {% endfor %}
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block content %}
{% include "include/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Lista Empleados</div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="150">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empleado in empleados %}
                        <tr>
                            <td>{{ empleado.id }}</td>
                            <td>{{ empleado.first_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento }}</td>
                            <td>
                                <a class="button success" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a>
                            </td>
                            <td>
                                <a class="button alert" href="{% url 'persona_app:Eliminar_empleado' empleado.id %}">Eliminar</a>
                            </td>

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                            </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                            {% if pagina == page_obj.number %}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}">{{ pagina }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/persona/success.html
<h1>Felicitaciones se ha guardado correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
    Edita empleado
{% endblock title %}


{% block content %}


{% include "include/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">  Modificar empleado</h1>
        <div class="cell">
            <form class="grid-x" method="post">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div> 
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }} 
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades extras:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
<h1>Modificar datos del empleado</h1>
<form method="post">{% csrf_token %}

    {{form.as_p}}
    <button type="submit">Actualizar</button>
</form>