applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="departamento_app"

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
    'departamento-lista/',
    views.DepartamentoListView.as_view(),
    name='departamento_list' ),
    path('new-departamento/', 
    views.NewDepartamentoView.as_view(), 
    name='nuevo_departamento/'
    ),
]

applications/personas/urls.py
from django.urls import path
from .views import ( lisAllEmpleados,
ListByAreaEmpleado,
ListEmpleadoByKword,
ListHabilidadesEmpleados,
EmpleadoDetailView,                    
EmpleadoCreateView,
SuccessView, EmpleadoUpdateView,EmpleadoDeleteView,InicioView, ListaEmpleadosAdmin,

)

app_name='persona_app'

urlpatterns = [
    path('', InicioView.as_view()),
    path('listar-todos-empleados/', lisAllEmpleados.as_view()),
    path('buscar-empleado/', ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', ListHabilidadesEmpleados.as_view()),
    path(
    'ver-empleado/<pk>/',
    EmpleadoDetailView.as_view(),
    name='empleado_detail'
),

    path('add-empleado/', 
        EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path(
        'success/',
        SuccessView.as_view(),
        name='correcto'),
    path(
        'update-empleado/<pk>/',
        EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path(
        'delate-empleado/<pk>/',
        EmpleadoDeleteView.as_view(),
        name='Eliminar_empleado'),
    path(
        'ver-empleado/<pk>/',
        EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),

    path(
        'list-by-area/<subnombre>/',
        ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),

    path(
        'lista-empleados-admin/',
        ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from applications.departamento import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path('', include('applications.home.urls')),  # ahora la raíz '' apunta a home
    re_path('', include('applications.personas.urls')),
    re_path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

class Departamento(models.Model):
    nombre = models.CharField('Nombre', max_length=50, editable=False)
    subnombre = models.CharField('Nombre Corto', max_length=50, unique=True)
    activo = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Áreas de la empresa'
        ordering=['-nombre']
        unique_together=('nombre','subnombre')


    def __str__(self):
        return f"{self.id} - {self.nombre} - {self.subnombre}"

applications/departamento/forms.py
from django import forms

class NewDepartamentoForms(forms.Form):
    nombre = forms.CharField(max_length=50, label="Departamento")
    short_name = forms.CharField(max_length=20, label="Short name")

applications/departamento/views.py
#from django.shortcuts import render
from django.views.generic.edit import FormView


from .models import Departamento
from applications.personas.models import Empleado   
from .forms import NewDepartamentoForms

from django.views.generic import (ListView)


class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name='departamentos'

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForms
    success_url = '/'

    def form_valid(self, form):
        Departamento.objects.create(
            nombre=form.cleaned_data['nombre'],
            subnombre=form.cleaned_data['short_name']
        )
        return super().form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista departamentos

{% endblock title %}

{% block content %}
    {% include "include/header.html" %}


    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.nombre }}</td>
                            <td>{{ departamento.subnombre }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.subnombre %}">Ver Empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}Registrar Departamento{% endblock %}

{% block content %}
{% include "include/header.html" %}

<div class="grid-container">
    <h1>Registrar Departamento</h1>

    <form method="post" class="grid-x grid-margin-x">
    {% csrf_token %}

    <div class="medium-6 cell">
        <label>Departamento</label>
        {{ form.nombre }}
    </div>

    <div class="medium-6 cell">
        <label>Short name</label>
        {{ form.short_name }}
    </div>

    <div class="cell">
        <button type="submit" class="button success">
            Guardar
        </button>
    </div>
</form>

</div>

{% endblock %}